### ISSUE TITLE
Refactor Python code to match PEP8 conventions

### ISSUE THREAD

**Issue by lalmeida32** [courselab/sucury#1]
- There are 3 character whitespaces for indentation, instead of 4 characters
- There are many trailing whitespaces
- The function "drawGrid" is not named using "snake_case", as required by CONTRIBUTING.md

**Comment by EggHeadTimothy** [comment]
Hi, I can help you with this. Do you want to assign it to me?

**Comment by lalmeida32** [comment]
Hi, how are you doing?
Sure, I already made a [PR](https://github.com/courselab/sucury/pull/5) solving the problems I have described, but I think there is more to do.
For example, none of the current functions have docstrings describing them, but I don't know if it should be addressed in this issue or a new one.

**Comment by EggHeadTimothy** [comment]
Would you like to create a new issue for docstrings and assign it to me?

**Comment by monacofj** [comment]
PR #5 is merged.
