### ISSUE TITLE
Loss of already implemented functionalities and return of bugs after a commit

### ISSUE THREAD

**Issue by Zeronevi** [courselab/sucury#125]
After the https://github.com/courselab/sucury/commit/cc302a121187fb08c094bfd176832f1abd646507 commit, many of the already implemented features and bug-fixes were lost. Some of those features were re-implemented again in the development branch and pending pull requests depend in either pre-cc302a1 development branch or the changes made after this commit.

Examples: 
(Change implemented - Same change re-implemented after the commit)
Prevents the snake from turning back: #15   - #118
Fixed snake dying randomly: #20   - #123 
Added WASD controls: #26  - feature lost and not re-implemented

Other functions may be lost. If you find any missing features that were there, reply on this message.

**Comment by angelobguido** [comment]
I think they are all re-implemented now.

**Comment by jotagenazar** [comment]
From what I could understand from the listed changes' code, and after some local testing, it does seem like the changes are all re-implemented. If no other missing feature is found, I think we can close the issue
