### ISSUE TITLE
Snake randomly dies after eating apple

### ISSUE THREAD

**Issue by monacofj** [courselab/sucury#14]
**Describe the bug**
The snake sometimes dies immediately after eating an apple.

**To Reproduce**
1.Start the game
2. Play for some time (30 or 40 sec)

**Expected behavior**
After collecting some apples, the snake would die when collecting the next one.

**Screenshots**
NA

**Platform:**
 - OS: [e.g. Linux]
 - Version [Ubuntu 22.04]

**Additional context**
Please, confirm reproductibility.

**Comment by Zeronevi** [comment]
Bug reproduced.

**Comment by ThiagoSDQ** [comment]
Started investigating this, when the snake eats an apple there is this code
```
snake.tail.append(pygame.Rect(snake.head.x, snake.head.x, GRID_SIZE, GRID_SIZE))
```
It should be `snake.head.x, snake.head.y` instead of `snake.head.x, snake.head.x`. However if we just do that the snake will dies every time it eats.

**Comment by ThiagoSDQ** [comment]
When the snake eats, instead of immediately appending a block to the tail, we could set a state saying that it should grow on the next update. Then on the update if it is marked as true we just don't pop the last tail block.

**Comment by monacofj** [comment]
Good idea, indeed!
