### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by ThiagoSDQ** [courselab/sucury#16]
We could add a requirements.txt file to keep track of dependencies as the project grows and make it easier for everyone to use the same versions so that things like bugs can be reproduced more easily.

**Comment by lucasgpulcinelli** [comment]
I am able to work on that. Also, in the same subject of development setup, a shell.nix file for nixos users would be ideal, I am also able to share the one I made in a new pull request that will be opened shortly.
