### ISSUE TITLE
Apple generation

### ISSUE THREAD

**Issue by g-faccini** [courselab/sucury#21]
I think it would be better if the apple could not be generated in a position already occupied by the body of the snake. Currently it is possible that the apple is generated on top of the snake and thus, the player is not able to see where it spawned.

**Comment by g-faccini** [comment]
> Maybe related to #22 ?

Yes. My idea is to change the apple class so it keeps a list of valid positions where it can be generated. That should fix #22 as well.

**Comment by monacofj** [comment]
> > Maybe related to #22 ?
> 
> Yes. My idea is to change the apple class so it keeps a list of valid positions where it can be generated. That should fix #22 as well.

Or you could just select at random and check if it's empty; retry otherwise.
