### ISSUE TITLE
No apple spawning in some cases

### ISSUE THREAD

**Issue by rogerllube** [courselab/sucury#22]
Sometimes the apple simply does not spawn on the map

1. Play the game for some time
2. It may happen at any time (It´s a little rare, but it happens)

Whenever an apple is eaten another one is supposed to spawn on the map

**Screenshots**

**Platform:**
 - OS: Linux
 - Version: Ubuntu 22.04

I suppose it has to do with the apple spawning and being eaten in the same frame, but more testing is required to find the cause

**Comment by monacofj** [comment]
Could it be spawning below the snake's body?
In any case, the spawn function might check whether the randomly selected position is empty and pick another position if it's not.
