### ISSUE TITLE
Game window not fitting screen

### ISSUE THREAD

**Issue by rogerllube** [courselab/sucury#23]
The game window does not fit the screen in some lower resolution monitors

1. It should happen if monitor is in a resolution lower than FHD

Game should adapt its size depending on monitor resolution or should be set to a size that accomodates all monitors and have the possibility of resizing

**Platform:**
 - OS: Linux
 - Version Ubuntu 22.04

Game window size is set to 800x800px, for monitors with less than FHD resolution that is bigger than the vertical size of the monitor

**Comment by VictorLutes** [comment]
![image](https://github.com/courselab/sucury/assets/61762690/56404d8a-1084-4b94-9888-9b14ecafccf2)
****
Also reproducible if you have two screens

    OS: Windows
    Version 11
