### ISSUE TITLE
Apple growing in an invalid location

### ISSUE THREAD

**Issue by GusSampaio** [courselab/sucury#27]
An apple can spawn in a location where the snake's body is, which in theory would be an invalid location and could disrupt the user's experience as the snake grows.

There is no way to force reproduction of this bug just by playing the game.

One way to solve this out is to allow the apple spawn only on a local that there is no snake part.

 - OS: Windows
 - Version Windows 11

**Comment by g-faccini** [comment]
This problem was already addressed on issue #21.

**Comment by GusSampaio** [comment]
I haven't see that before. Tks.
