### ISSUE TITLE
The arrow shouldn't work in the opposite direction

### ISSUE THREAD

**Issue by yp1plus** [courselab/sucury#30]
When playing, if the snake is the size of more than two squares, when it is looking up and the player press down, the head of snake tries to go down, and the snake dies because of collision with itself. The same happens in all the other directions.

1. When the snake (size more than two squares) is looking up, the player press down;
2. When the snake (size more than two squares) is looking to the right, the player press left;
3. When the snake (size more than two squares) is looking to the left, the player press right;
4. When the snake (size more than two squares) is looking down, the player press up;

In this case, you get game over, but it is not believable a snake going inside itself. So, it should not be allowed the commands for the player in the opposite direction of the snake.

**Platform:**
 - OS: MacOs Monterey
 - Version 12.3

**Comment by yp1plus** [comment]
The pull request addressing this issue: https://github.com/courselab/sucury/pull/31

**Comment by g-faccini** [comment]
I believe this problem has already been fixed. Check (closed) issue #7. Maybe you have the wrong version?

**Comment by yp1plus** [comment]
I was checking the main branch. I didn’t know we are working with the developer branch. My bad !

**Comment by monacofj** [comment]
> I was checking the main branch. I didn’t know we are working with the developer branch. My bad !

Oh! You have read `docs\CONTRIBUTING.md`, right??

**Comment by yp1plus** [comment]
> > I was checking the main branch. I didn’t know we are working with the developer branch. My bad !
> 
> Oh! You have read `docs\CONTRIBUTING.md`, right??

Yes, I followed the guidelines for commits and branches, but I confess it is not clear reading in the doc how to procedure to open a pull request. Just it says : 'Submit your support branch and mark it as a pull/merge request'.
